// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Schemas.Avros
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// schema para exemplificar como criar schemas
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class Curso : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Curso\",\"doc\":\"schema para exemplificar como criar schema" +
				"s\",\"namespace\":\"Schemas.Avros\",\"fields\":[{\"name\":\"Id\",\"doc\":\"id do curso\",\"type\"" +
				":\"string\"},{\"name\":\"Descricao\",\"doc\":\"descricao do curso\",\"type\":\"string\"}]}");
		/// <summary>
		/// id do curso
		/// </summary>
		private string _Id;
		/// <summary>
		/// descricao do curso
		/// </summary>
		private string _Descricao;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return Curso._SCHEMA;
			}
		}
		/// <summary>
		/// id do curso
		/// </summary>
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				this._Id = value;
			}
		}
		/// <summary>
		/// descricao do curso
		/// </summary>
		public string Descricao
		{
			get
			{
				return this._Descricao;
			}
			set
			{
				this._Descricao = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Id;
			case 1: return this.Descricao;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Id = (System.String)fieldValue; break;
			case 1: this.Descricao = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
